"""create initial table

Revision ID: 083c66a3c634
Revises: 729196e349df
Create Date: 2024-07-27 23:33:42.468202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '083c66a3c634'
down_revision: Union[str, None] = '729196e349df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    print("Starting the initial migration. Creation of the table guestbook...")
    if op.get_bind().dialect.has_table(op.get_bind(), 'guestbook'):
        op.drop_index(op.f('ix_guestbook_id'), table_name='guestbook')
        op.drop_table('guestbook')
        print("Table guestbook already exists. Dropping table guestbook...")
    op.create_table('guestbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guestbook_id'), 'guestbook', ['id'], unique=False)
    print("Table guestbook created successfully. Please check the database for the table.")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guestbook_id'), table_name='guestbook')
    op.drop_table('guestbook')
    # ### end Alembic commands ###
