"""fixed new model init

Revision ID: 8d42d5f388a4
Revises: 083c66a3c634
Create Date: 2024-07-30 14:15:56.233314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel.sql.sqltypes    

# revision identifiers, used by Alembic.
revision: str = '8d42d5f388a4'
down_revision: Union[str, None] = '083c66a3c634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guestbook', 'message',
               existing_type=mysql.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
    op.alter_column('guestbook', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index('ix_guestbook_id', table_name='guestbook')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_guestbook_id', 'guestbook', ['id'], unique=False)
    op.alter_column('guestbook', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('guestbook', 'message',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=mysql.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
